import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../../styles/bootstrap.min.css";
import BootstrapClient from "./components/BootstrapClient";
import "./globals.css";
import "../../styles/app.css";
import Navbar from "./components/Navbar";
import Foot from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <BootstrapClient />
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased d-flex flex-column vh-100`}
      >
        <main className="container mt-5 px-0">
          <Navbar />
          {children}
        </main>
        <Foot />
      </body>
    </html>
  );
}
